kind: Service
apiVersion: v1
metadata:
  name: reactappservice
spec:
  selector:
    name: deployment
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31231
  type: NodePort
---
kind: Deployment
apiVersion: apps/v1
metadata:
   name: mydeployments
spec:
   replicas: 2
   selector:     
    matchLabels:
     name: deployment
   template:
     metadata:
       name: reactapp
       labels:
         name: deployment
     spec:
      containers:
        - name: reactapp
          image: manashwi/reactapp:v1
          ports:
            - containerPort: 8080
